fixtures:
  repositories:
    puppet-enterprise-modules:
      repo: 'git@github.com:puppetlabs/puppet-enterprise-modules.git'
      ref: 'origin/kearney'
      target: 'spec/fixtures'
    yumrepo_core:
      repo: "git@github.com:puppetlabs/puppetlabs-yumrepo_core.git"
      ref: origin/master
    augeas_core:
      repo: "git@github.com:puppetlabs/puppetlabs-augeas_core.git"
      ref: origin/master
    stdlib:
        repo: "git@github.com:puppetlabs/puppetlabs-stdlib.git"
        ref: origin/master
    pe_r10k:
        repo: "git@github.com:puppetlabs/puppetlabs-pe_r10k.git"
        ref: origin/2016.2.x
    docker:
        repo: "git@github.com:puppetlabs/puppetlabs-docker.git"
        ref: origin/master
    cron_core:
        repo: "git@github.com:puppetlabs/puppetlabs-cron_core.git"
        ref: origin/master
    translate:
        repo: "git@github.com:puppetlabs/puppetlabs-translate.git"
  symlinks:
     puppet_enterprise: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/puppet_enterprise"
     pe_install: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/pe_install"
     pe_concat: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/pe_concat"
     pe_postgresql: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/pe_postgresql"
     pe_java_ks: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/pe_java_ks"
     pe_inifile: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/pe_inifile"
     pe_hocon: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/pe_hocon"
     pe_puppet_authorization: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/pe_puppet_authorization"
     puppet_authorization: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/puppet_authorization"
     cd4pe: "#{source_dir}"
